# Generated by Django 5.1 on 2024-09-03 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_remove_userhistory_anime_remove_userhistory_episode"),
        ("watch", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="recommendations",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="studios",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="title",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="trailer",
        ),
        migrations.RemoveField(
            model_name="animerelation",
            name="relation",
        ),
        migrations.RemoveField(
            model_name="animerelation",
            name="anime",
        ),
        migrations.RemoveField(
            model_name="animeepisode",
            name="anime",
        ),
        migrations.RemoveField(
            model_name="animeseason",
            name="anime",
        ),
        migrations.DeleteModel(
            name="AnimeGenre",
        ),
        migrations.DeleteModel(
            name="AnimeStudio",
        ),
        migrations.DeleteModel(
            name="AnimeTitle",
        ),
        migrations.DeleteModel(
            name="AnimeTrailer",
        ),
        migrations.DeleteModel(
            name="AnimeRelation",
        ),
        migrations.DeleteModel(
            name="AnimeEpisode",
        ),
        migrations.DeleteModel(
            name="Anime",
        ),
        migrations.DeleteModel(
            name="AnimeSeason",
        ),
    ]
