# Generated by Django 5.1 on 2024-09-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("watch", "0002_remove_anime_genres_remove_anime_recommendations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeGenre",
            fields=[
                ("genre_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AnimeStudio",
            fields=[
                ("studio_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AnimeTitle",
            fields=[
                ("title_id", models.AutoField(primary_key=True, serialize=False)),
                ("english", models.CharField(max_length=255)),
                ("romaji", models.CharField(max_length=255)),
                ("native", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AnimeTrailer",
            fields=[
                ("trailer_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=255)),
                ("site", models.CharField(max_length=255)),
                ("thumbnail", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Anime",
            fields=[
                ("anime_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=255, unique=True)),
                ("malId", models.IntegerField()),
                ("description", models.TextField()),
                ("image", models.URLField()),
                ("cover", models.URLField()),
                ("countryOfOrigin", models.CharField(max_length=255)),
                ("popularity", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("releaseDate", models.IntegerField()),
                ("totalEpisodes", models.IntegerField()),
                ("currentEpisode", models.IntegerField()),
                ("rating", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("type", models.CharField(max_length=255)),
                ("season", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                (
                    "recommendations",
                    models.ManyToManyField(blank=True, to="watch.anime"),
                ),
                ("genres", models.ManyToManyField(to="watch.animegenre")),
                ("studios", models.ManyToManyField(to="watch.animestudio")),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="watch.animetitle",
                    ),
                ),
                (
                    "trailer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="watch.animetrailer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimeEpisode",
            fields=[
                ("episode_id", models.AutoField(primary_key=True, serialize=False)),
                ("episode_number", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
                ("air_date", models.DateField()),
                ("filler", models.BooleanField(default=False)),
                ("image", models.URLField()),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="watch.anime"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimeRelation",
            fields=[
                ("relation_id", models.AutoField(primary_key=True, serialize=False)),
                ("relationType", models.CharField(max_length=255)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="watch.anime"
                    ),
                ),
                (
                    "related_anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="watch.anime",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimeSeason",
            fields=[
                ("season_id", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("poster", models.URLField()),
                ("isCurrent", models.BooleanField(default=False)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="watch.anime"
                    ),
                ),
            ],
        ),
    ]
