# Generated by Django 5.1 on 2024-09-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="countryOfOrigin",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="currentEpisode",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="genres",
            field=models.ManyToManyField(blank=True, to="watch.animegenre"),
        ),
        migrations.AlterField(
            model_name="anime",
            name="popularity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="releaseDate",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="season",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="studios",
            field=models.ManyToManyField(blank=True, to="watch.animestudio"),
        ),
    ]
