# Generated by Django 5.1 on 2024-09-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0004_alter_anime_countryoforigin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
