# Generated by Django 5.1 on 2024-09-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0005_anime_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animetitle",
            name="english",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="animetitle",
            name="native",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
