# Generated by Django 5.1 on 2024-09-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0006_alter_animetitle_english_alter_animetitle_native"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="color",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
