# Generated by Django 5.1 on 2024-09-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0007_alter_anime_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="totalEpisodes",
            field=models.IntegerField(null=True),
        ),
    ]
