# Generated by Django 5.1 on 2024-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0010_anime_end_date_anime_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animetitle",
            name="romaji",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
