# Generated by Django 5.1 on 2024-09-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0011_alter_animetitle_romaji"),
    ]

    operations = [
        migrations.AddField(
            model_name="animeepisode",
            name="zEpisodeId",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
