# Generated by Django 5.1 on 2024-09-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0013_alter_anime_malid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="rating",
            field=models.IntegerField(null=True),
        ),
    ]
