# Generated by Django 5.1 on 2024-09-03 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0015_alter_anime_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="title",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anime",
                to="watch.animetitle",
            ),
        ),
        migrations.AlterField(
            model_name="anime",
            name="trailer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anime",
                to="watch.animetrailer",
            ),
        ),
    ]
