# Generated by Django 5.1 on 2024-09-03 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0016_alter_anime_title_alter_anime_trailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="trailer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anime",
                to="watch.animetrailer",
            ),
        ),
    ]
