# Generated by Django 5.1 on 2024-09-03 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0019_alter_animeepisode_episode_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animeepisode",
            name="episode_number",
        ),
    ]
