# Generated by Django 5.1 on 2024-09-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0020_remove_animeepisode_episode_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="dub",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="anime",
            name="sub",
            field=models.IntegerField(default=0),
        ),
    ]
