# Generated by Django 5.1 on 2024-09-04 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watch", "0021_anime_dub_anime_sub"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="recommendations",
        ),
        migrations.DeleteModel(
            name="AnimeRelation",
        ),
    ]
