# Generated by Django 5.1 on 2024-09-30 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_profile",
            "0011_alter_userhistory_anime_alter_userhistory_episode_and_more",
        ),
        ("watch", "0022_remove_anime_recommendations_delete_animerelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anime",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="studios",
        ),
        migrations.RemoveField(
            model_name="animetitle",
            name="anime",
        ),
        migrations.RemoveField(
            model_name="animeseason",
            name="anime",
        ),
        migrations.RemoveField(
            model_name="animeepisode",
            name="anime",
        ),
        migrations.RemoveField(
            model_name="animetrailer",
            name="anime",
        ),
        migrations.DeleteModel(
            name="AnimeGenre",
        ),
        migrations.DeleteModel(
            name="AnimeStudio",
        ),
        migrations.DeleteModel(
            name="AnimeTitle",
        ),
        migrations.DeleteModel(
            name="AnimeSeason",
        ),
        migrations.DeleteModel(
            name="AnimeEpisode",
        ),
        migrations.DeleteModel(
            name="Anime",
        ),
        migrations.DeleteModel(
            name="AnimeTrailer",
        ),
    ]
