# Generated by Django 5.1 on 2024-08-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_access_token",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="discord_refresh_token",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="discord_token_type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
