# Generated by Django 5.1 on 2024-08-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_user_discord_access_token_user_discord_refresh_token_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_avatar",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="discord_banner",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
