# Generated by Django 5.1 on 2024-08-25 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnimeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anime_id", models.IntegerField()),
                ("anime_mal_id", models.IntegerField()),
                ("status", models.CharField(max_length=16)),
                ("score", models.IntegerField()),
                ("episodes_watched", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Anime Lists",
            },
        ),
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anime_id", models.IntegerField()),
                ("episode", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Histories",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_layout", models.CharField(default="classic", max_length=16)),
                ("title_language", models.CharField(default="english", max_length=16)),
                (
                    "character_name_language",
                    models.CharField(default="romaji", max_length=16),
                ),
                ("default_language", models.CharField(default="sub", max_length=16)),
                (
                    "default_provider",
                    models.CharField(default="gogoanime", max_length=16),
                ),
                (
                    "default_watch_page",
                    models.CharField(default="watch", max_length=16),
                ),
                ("show_history_on_home", models.BooleanField(default=True)),
                ("auto_skip_intro", models.BooleanField(default=False)),
                ("auto_play_video", models.BooleanField(default=False)),
                ("auto_next_episode", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Preferences",
            },
        ),
    ]
