# Generated by Django 5.1 on 2024-08-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="smart_mal_sync",
            field=models.BooleanField(default=False),
        ),
    ]
