# Generated by Django 5.1 on 2024-09-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
