# Generated by Django 5.1 on 2024-09-03 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_userhistory_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhistory",
            name="anime_id",
        ),
        migrations.RemoveField(
            model_name="userhistory",
            name="episode",
        ),
        migrations.RemoveField(
            model_name="userhistory",
            name="last_watched",
        ),
        migrations.RemoveField(
            model_name="userhistory",
            name="time_watched",
        ),
    ]
