# Generated by Django 5.1 on 2024-08-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0002_userpreferences_smart_mal_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="accent_colour",
            field=models.CharField(default="purple", max_length=16),
        ),
    ]
