# Generated by Django 5.1 on 2024-08-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0003_userpreferences_accent_colour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhistory",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="userhistory",
            name="time_watched",
            field=models.IntegerField(default=0),
        ),
    ]
