# Generated by Django 5.1 on 2024-08-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0004_remove_userhistory_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="last_watched",
            field=models.BooleanField(default=False),
        ),
    ]
