# Generated by Django 5.1 on 2024-08-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0005_userhistory_last_watched"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="ingrain_sub_subtitles_in_dub",
            field=models.BooleanField(default=False),
        ),
    ]
