# Generated by Django 5.1 on 2024-09-03 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0005_userhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userhistory",
            name="anime",
        ),
        migrations.RemoveField(
            model_name="userhistory",
            name="episode",
        ),
    ]
