# Generated by Django 5.1 on 2024-09-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0010_userhistory_time_watched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistory",
            name="anime",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="episode",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="UserAnimeList",
        ),
    ]
