# Generated by Django 5.1 on 2024-09-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_profile",
            "0011_alter_userhistory_anime_alter_userhistory_episode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="anime_cover_image",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userhistory",
            name="anime_title_english",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userhistory",
            name="anime_title_native",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userhistory",
            name="anime_title_romaji",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
