# Generated by Django 5.1 on 2024-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0013_userhistory_episode_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistory",
            name="anime_cover_image",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="anime_title_english",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="anime_title_native",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="anime_title_romaji",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
